version: '2'

services:
    gateway:
        build:
            context: .
            dockerfile: ./gateway/Dockerfile
        env_file:
            - ./gateway/.env
        ports:
            - 2727:2727
        links:
            - security
            - service3
        depends_on:
            - security
            - service3
            - db
        networks:
            - ms 
    security:
        build:
            context: .
            dockerfile: ./security/Dockerfile
        env_file:
            - ./security/.env
        networks:
            - ms 

    service3:
        build:
            context: .
            dockerfile: ./service3/Dockerfile
        env_file:
            - ./service3/.env
        networks:
            - ms 
    db:
        image: mysql:5.7
        container_name: "database"
        ports: 
          - 3306:3306
        environment:
          MYSQL_ROOT_HOST: "db"
          MYSQL_USER: "haithem"
          MYSQL_PASSWORD: "aden"
          MYSQL_DATABASE: "microservices"
          MYSQL_ROOT_PASSWORD: "root"
        networks:
            - ms 
        volumes:
            - ./data/mysql:/var/lib/mysql 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmn_container
        depends_on:
          - db
        environment: 
          PMA_HOST: "db"
          PMA_PORT: "3306"
        ports:
          - 9091:80
        restart: always
        networks:
          - ms
          # Networks to be created to facilitate communication between containers
networks:
  ms:
    driver: bridge
